import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

UVX_PATH = "/Users/mustafasahin/.local/bin/uvx"
CMD = [
    UVX_PATH,
    "--offline",
    "--from",
    "mcpforunityserver==10.2.0",
    "mcp-for-unity",
    "--transport",
    "stdio"
]


def send_rpc(proc, req_id, method, params=None):
    payload = {
        "jsonrpc": "2.0",
        "id": req_id,
        "method": method,
        "params": params or {}
    }
    raw = json.dumps(payload) + "\n"
    proc.stdin.write(raw.encode("utf-8"))
    proc.stdin.flush()

    while True:
        line = proc.stdout.readline().decode("utf-8").strip()
        if not line:
            continue
        try:
            res = json.loads(line)
            if res.get("id") == req_id:
                return res
        except json.JSONDecodeError:
            continue


def call_tool(proc, req_id, name, arguments):
    """Calls an MCP tool and returns (structured_content, is_error, raw_text).

    manage_build's real result is JSON *text* inside result.content[0].text;
    result.structuredContent mirrors it when the call succeeds, but on a
    validation error (e.g. an unknown/misspelled argument) there is no
    structuredContent at all and result.isError is true - that must be
    checked explicitly, or a bad argument silently looks like "no job_id"
    instead of the actual rejection.
    """
    res = send_rpc(proc, req_id, "tools/call", {"name": name, "arguments": arguments})
    result = res.get("result", {})
    is_error = bool(result.get("isError"))
    raw_text = ""
    content_list = result.get("content") or []
    if content_list and isinstance(content_list[0], dict):
        raw_text = content_list[0].get("text", "")

    structured = result.get("structuredContent")
    if structured is None:
        # No structuredContent (typically a tool-call/validation error): fall back
        # to parsing the text block so callers still see *something* useful.
        try:
            structured = json.loads(raw_text) if raw_text else {}
        except json.JSONDecodeError:
            structured = {}

    return structured, is_error, raw_text


def ensure_post_install_deployment_target(podfile):
    """Some pods (Google-Mobile-Ads-SDK, GoogleUserMessagingPlatform) ship a lower
    IPHONEOS_DEPLOYMENT_TARGET than the project's minimum, which Xcode now rejects
    outright once it falls outside the supported range. EDM4U regenerates the
    Podfile fresh on every Unity export with no post_install hook, so this has to
    be re-applied each time rather than fixed by hand once.
    """
    text = podfile.read_text()
    if "post_install do |installer|" in text:
        return

    match = re.search(r"platform\s*:ios,\s*['\"]([\d.]+)['\"]", text)
    min_version = match.group(1) if match else "15.0"

    hook = f"""
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if deployment_target.nil? || deployment_target.to_f < {min_version}.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '{min_version}'
      end
    end
  end
end
"""
    podfile.write_text(text.rstrip("\n") + "\n" + hook)
    print(f"🔧 Podfile'a post_install hook eklendi (min iOS {min_version}).")


def run_pod_install(output_path):
    """Runs `pod install` in the exported Xcode project so the Podfile
    (Google-Mobile-Ads-SDK etc., regenerated by EDM4U on every export) is
    actually linked. Without this, the plain .xcodeproj fails to link with
    undefined symbols like _CGSizeFromGADAdSize.
    """
    podfile = Path(output_path) / "Podfile"
    if not podfile.exists():
        print("ℹ️  Podfile yok, pod install adımı atlanıyor.")
        return

    ensure_post_install_deployment_target(podfile)

    pod_bin = shutil.which("pod")
    if not pod_bin:
        print("\n⚠️  CocoaPods kurulu değil (`pod` bulunamadı).")
        print("   Kurulum: brew install cocoapods")
        print(f"   Sonra: cd {output_path} && pod install")
        return

    print("📦 pod install çalıştırılıyor...")
    result = subprocess.run([pod_bin, "install"], cwd=output_path)
    if result.returncode != 0:
        print("\n⚠️  pod install başarısız oldu, yukarıdaki hatayı kontrol et.")
        return

    print("✅ pod install tamamlandı.")


def main():
    print("🚀 MCP Sunucusu başlatılıyor...")
    proc = subprocess.Popen(
        CMD,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    req_id = 1

    print("🤝 MCP Handshake yapılıyor...")
    send_rpc(proc, req_id, "initialize", {
        "protocolVersion": "2024-11-05",
        "capabilities": {},
        "clientInfo": {"name": "auto-builder", "version": "1.0"}
    })
    req_id += 1

    print("📦 iOS Build tetikleniyor...")
    structured, is_error, raw_text = call_tool(proc, req_id, "manage_build", {
        "action": "build",
        "target": "iOS",
        # manage_build takes snake_case arguments - "outputPath" is silently
        # rejected as an unknown keyword (Pydantic validation error) and the
        # build never starts.
        "output_path": "Builds/iOS"
    })
    req_id += 1

    if is_error or not structured.get("success", False):
        print("\n❌ Build başlatılamadı:")
        print(raw_text or json.dumps(structured, indent=2))
        proc.terminate()
        sys.exit(1)

    job_id = structured.get("data", {}).get("job_id")
    poll_interval = structured.get("_mcp_poll_interval", 5.0)

    if not job_id:
        print("\n❌ Build başlatıldı ama job_id alınamadı, durduruluyor:")
        print(raw_text or json.dumps(structured, indent=2))
        proc.terminate()
        sys.exit(1)

    print(f"⏳ Build kuyruğa alındı (Job: {job_id}). Durum sorgulanıyor...")

    # A job that hasn't shown up as "succeeded"/"failed" yet is simply still
    # running - only bail out early on an explicit failure result. Missing
    # job_id is handled above so it can never silently poll job_id=None,
    # which the server answers with the *last* completed build instead of
    # an error, making a build that never started look like a success.
    while True:
        time.sleep(poll_interval)
        structured, is_error, raw_text = call_tool(proc, req_id, "manage_build", {
            "action": "status",
            "job_id": job_id
        })
        req_id += 1

        if is_error:
            print("\n❌ Durum sorgulanamadı:")
            print(raw_text)
            break

        if not structured.get("success", False):
            print(f"⌛ Henüz hazır değil, tekrar denenecek... ({time.strftime('%H:%M:%S')})")
            continue

        data = structured.get("data", {})
        result_state = data.get("result")

        if result_state == "succeeded":
            print("\n🎉 Build başarıyla tamamlandı!")
            output_path = data.get("output_path", "Builds/iOS")
            print(f"📍 Xcode Proje Yolu: {output_path}")
            run_pod_install(output_path)
            print(f"👉 Sonraki adım: open {output_path}/Unity-iPhone.xcworkspace")
            break
        elif result_state == "failed":
            print("\n❌ Build başarısız oldu:")
            print(json.dumps(data, indent=2))
            break
        else:
            print(f"⌛ Derleme devam ediyor... ({time.strftime('%H:%M:%S')})")
            continue

    proc.terminate()


if __name__ == "__main__":
    main()
